# Generated by Django 6.0.3 on 2026-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chips_images/'),
        ),
    ]
