# Generated by Django 6.0.3 on 2026-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chips_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chips',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
